version: '2'

services:
  myapp:
    tty: true # Enables debugging capabilities when attached to this container.
    image: juanariza131/swift
    ports:
      - '8181:8181'
    volumes:
      - .:/app
